"""Initial revision

Revision ID: 454ea2ebebd6
Revises: 8cc685cea39e
Create Date: 2024-09-08 16:41:40.765195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '454ea2ebebd6'
down_revision: Union[str, None] = '8cc685cea39e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contexts')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contexts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('openai_key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('response', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='contexts_pkey')
    )
    # ### end Alembic commands ###
